from collections.abc import Sequence
from typing import overload


class Tensor:
    @overload
    def __init__(self, shape: Sequence[int]) -> None: ...
    @overload
    def __init__(self, shape: Sequence[int], values: Sequence[float]) -> None: ...
    @property
    def shape(self) -> list[int]: ...
    @property
    def rank(self) -> int: ...
    @property
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def to_list(self) -> list[float]: ...
    def add(self, other: Tensor) -> Tensor: ...
    def subtract(self, other: Tensor) -> Tensor: ...
    def multiply(self, other: Tensor) -> Tensor: ...
    def divide(self, other: Tensor) -> Tensor: ...
    def __add__(self, other: Tensor) -> Tensor: ...
    def __sub__(self, other: Tensor) -> Tensor: ...
    def __mul__(self, other: Tensor) -> Tensor: ...
    def __truediv__(self, other: Tensor) -> Tensor: ...


@overload
def add(lhs: int, rhs: int) -> int: ...
@overload
def add(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def subtract(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def multiply(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def divide(lhs: Tensor, rhs: Tensor) -> Tensor: ...
