#include <pybind11/pybind11.h>

#include "cinder/add.hpp"

namespace py = pybind11;

/**
 * @brief 定义 Python 扩展模块入口。Define the Python extension module entry point.
 *
 * @param module Python 模块对象（Python module object）。The Python module object.
 * @note 该函数由 PYBIND11_MODULE 宏（macro）生成并导出给 CPython。
 *       This function is generated by the PYBIND11_MODULE macro and exported to CPython.
 */
PYBIND11_MODULE(_core, module)
{
  module.doc() = "Native C++ extension module for cinder.";

  module.def(
      "add",
      &cinder::add,
      py::arg("lhs"),
      py::arg("rhs"),
      R"pbdoc(
      返回两个整数的和。

      Return the sum of two integers.
      )pbdoc");
}
